---
title: "TerrorismData"
author: "RSG"
date: "5 Oktober 2016"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

# Working directory

Assigning the working directory in my computer

```{r data, results='asis', tidy=TRUE, echo=FALSE}
setwd('C:/Users/Schmuziger/Documents/R_CDA')
```

# Importing and creating Dataset

```{r data, results='asis', tidy=TRUE, echo=FALSE}
dataset <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/terrorism/eu_terrorism_fatalities_by_country.csv")
```

# Descriptive statistics

```{r data, results='asis', tidy=TRUE, echo=FALSE}
summary(dataset)

mean(dataset$Germany)
var(dataset$Germany)
```

# Plots

Plotting German Data

```{r data, results='asis', tidy=TRUE, echo=FALSE}
plot(dataset$Germany)
hist(dataset$Germany)
```

# changing the data

```{r data, results='asis', tidy=TRUE, echo=FALSE}
BigCountries <- c("France", "Germany", "Spain", "United.Kingdom", "Italy", "Greece")
SmallCOuntries <- c("Luxembourg", "Denmark", "Belgium", "Portugal", "Ireland", "Netherlands")
```

# Dataset only Big Countries

```{r data, results='asis', tidy=TRUE, echo=FALSE}
summary(BigCountries)
```

# Analysis: subsetting datasets

```{r data, results='asis', tidy=TRUE, echo=FALSE}
d2001on <- subset(dataset, iyear >= 2001)
summary(d2001on)
d2001back <- subset(dataset, iyear < 2001)
summary(d2001back)
```

# % of Attacks per year in Germany before and after 2001

```{r data, results='asis', tidy=TRUE, echo=FALSE}
sum(d2001on$Germany)/14

sum(d2001back$Germany)/31
```

# % of Attacks per year in small and big countries
